apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: express-fe
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/phucdang1361998/infra.git'
    targetRevision: HEAD
    path: express-fe
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: express
  syncPolicy:
    automated:
      prune: true
      selfHeal: true