apiVersion: v1
kind: Service
metadata:
  name: express-fe-service
  namespace: express
spec:
  selector:
    app: express-fe
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP