apiVersion: apps/v1
kind: Deployment
metadata:
  name: express-fe
  labels:
    app: express-fe
  namespace: express
spec:
  replicas: 2
  selector:
    matchLabels:
      app: express-fe
  template:
    metadata:
      labels:
        app: express-fe
    spec:
      imagePullSecrets:
      - name: harbor-secret
      containers:
      - name: express-fe
        image: harbor.learnserver.online/express/express-fe:latest
        - containerPort: 80 
---
apiVersion: v1
kind: Service
metadata:
  name: express-fe-service
  namespace: express
spec:
  selector:
    app: express-fe
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP
